services:
  api:
    build: ./
    command: >
      sh -c "bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on: 
      - db  

  db:
    image: postgres 
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: password   
    volumes:
      - /app/tmp/db:/var/lib/postresql/data
